// src/components/Certifications.jsx
import { useState } from "react";
import certificationsData from "../data/certifications.json";
import CertificationCard from "./CertificationCard";

function Certifications() {
  const [certifications, setCertifications] = useState(certificationsData);

  return (
    <section
      id="certifications"
      className="flex flex-col justify-center items-start gap-16 py-24 px-12 sm:px-16 md:px-24 lg:px-36"
    >
      <h1 className="text-3xl sm:text-4xl md:text-5xl font-semibold dark:text-gray-200">
        Certifications
      </h1>
      <div className="flex flex-col items-center w-full">
        <div className="grid grid-cols1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
          {certifications.map((certification) => {
            return (
              <CertificationCard
                key={certification.course}
                course={certification.course}
                school={certification.school}
                date={certification.date}
                link={certification.link}
              />
            );
          })}
        </div>
      </div>
    </section>
  );
}

export default Certifications;

// src/components/Certifications.vue
<script setup>
import { defineAsyncComponent, ref, onMounted } from "vue";

const CertificationCard = defineAsyncComponent(() =>
  import("./CertificationCard.vue")
);
const certifications = ref([]);

onMounted(async () => {
  const response = await fetch("/data/data.json");
  const data = await response.json();
  certifications.value = data.certifications;
});
</script>

<template>
  <section
    class="pb-20 min-h-screen px-8 lg:px-32"
    id="certifications"
    data-aos="zoom-in-up"
  >
    <h2
      class="text-3xl md:text-4xl lg:text-5xl font-bold bg-gradient-to-r from-orange-400 to-pink-400 bg-clip-text text-transparent inline-block mt-12"
    >
      ./certifications
    </h2>

    <div v-if="certifications.length === 0" class="text-center">
      <p>Loading certifications...</p>
    </div>

    <!-- Grid for certifications -->
    <div class="grid grid-cols-1 md:grid-cols-3 gap-5 mt-12">
      <CertificationCard
        v-for="cert in certifications"
        :key="cert.course"
        :certification="cert"
      />
    </div>
  </section>
</template>
