// src/components/EducationCard.jsx
import React from "react";

function EducationCard({ degree, school, date, location, content, link }) {
  return (
    <li className="mb-10 ms-6">
      <span className="absolute flex items-center justify-center w-6 h-6 bg-blue-100 rounded-full -start-3 dark:bg-blue-600"></span>
      <h3 className="flex items-center mb-1 text-xl font-semibold text-gray-900 dark:text-white">
        {degree}
      </h3>
      <div className="mb-2">
        <a
          href={link}
          target="_blank"
          className="text-blue-500 hover:underline"
        >
          {school}
        </a>
      </div>
      <div className="block text-sm mb-3 text-gray-400 dark:text-gray-500">
        {date} | {location}
      </div>
      <p className="mb-4 text-gray-500 dark:text-gray-400">
        {content
          ? content.split("\n").map((item, index) => (
              <React.Fragment key={index}>
                {item}
                <br />
              </React.Fragment>
            ))
          : null}
      </p>
    </li>
  );
}

export default EducationCard;

// src/components/EducationCard.vue
<script setup>
defineProps({
  education: {
    type: Object,
    required: true,
  },
});
</script>

<template>
  <article class="bg-slate-800 text-white p-4 rounded-lg shadow-lg">
    <div class="flex flex-col justify-between gap-2 h-full">
      <div>
        <div>
          <div class="flex justify-between">
            <h3 class="text-2xl font-bold">{{ education.degree }}</h3>
            <p class="text-sm text-gray-500">{{ education.date }}</p>
          </div>
          <p class="text-lg text-gray-400">
            <span class="font-semibold">{{ education.school }}</span> |
            <span class="text-sm"> {{ education.location }}</span>
          </p>
        </div>

        <div>
          <ul class="list-disc text-sm text-gray-300">
            <li
              v-for="(item, index) in education.content.split('\n')"
              :key="index"
              class="list-none"
            >
              {{ item }}
            </li>
          </ul>
        </div>
      </div>

      <div>
        <a
          :href="education.link"
          target="_blank"
          class="text-sm font-semibold bg-gradient-to-r from-orange-400 to-pink-400 bg-clip-text text-transparent group hover:bg-gradient-to-r hover:from-pink-400 hover:to-orange-400 transition-colors duration-300"
        >
          Visit school website
        </a>
      </div>
    </div>
  </article>
</template>
