// src/components/Projects.jsx
import { useState } from "react";
import projectsData from "../data/projects.json";
import ProjectCard from "./ProjectCard";

function Projects() {
  const [projects, setProjects] = useState(projectsData);

  return (
    <section
      id="projects"
      className="flex flex-col justify-center items-start gap-16 py-24 px-12 sm:px-16 md:px-24 lg:px-36"
    >
      <h1 className="text-3xl sm:text-4xl md:text-5xl font-semibold dark:text-gray-200">
        Projects
      </h1>
      <div className="flex flex-col items-center w-full">
        <div className="grid grid-cols1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
          {projects.map((project) => {
            return (
              <ProjectCard
                key={project.title}
                title={project.title}
                date={project.date}
                content={project.content}
                stack={project.stack}
                link={project.link}
              />
            );
          })}
        </div>
      </div>
    </section>
  );
}

export default Projects;

// src/components/Projects.vue
<script setup>
import { defineAsyncComponent, ref, onMounted } from "vue";

const ProjectCard = defineAsyncComponent(() => import("./ProjectCard.vue"));
const projects = ref([]);

onMounted(async () => {
  const response = await fetch("/data/data.json");
  const data = await response.json();
  projects.value = data.projects;
});
</script>

<template>
  <section
    class="pb-20 min-h-screen px-8 lg:px-32"
    id="projects"
    data-aos="zoom-in-up"
  >
    <h2
      class="text-3xl md:text-4xl lg:text-5xl font-bold bg-gradient-to-r from-orange-400 to-pink-400 bg-clip-text text-transparent inline-block mt-12"
    >
      ./projects
    </h2>

    <div v-if="projects.length === 0" class="text-center">
      <p>Loading projects...</p>
    </div>

    <div class="grid grid-cols-1 md:grid-cols-2 gap-5 mt-12 items-stretch">
      <ProjectCard
        v-for="project in projects"
        :key="project.title"
        :project="project"
      />
    </div>
  </section>
</template>
