// src/components/ProjectCard.jsx
import { FaLink } from "react-icons/fa6";
import { FaGithub } from "react-icons/fa";

function ProjectCard({ title, date, content, stack, link }) {
  return (
    <div className="max-w-sm p-6 bg-white border border-stone-200 rounded-lg dark:bg-gray-800 dark:border-gray-700">
      <div className="flex flex-col justify-between h-full">
        <div>
          <div className="flex flex-wrap items-center justify-between gap-2">
            <p className="text-2xl font-bold mb-1 text-gray-900 dark:text-white">
              {title}
            </p>
            <div className="flex gap-2">
              {link.deployed !== "" ? (
                <FaLink
                  onClick={() => window.open(link.deployed, "_blank")}
                  className="cursor-pointer dark:text-white"
                />
              ) : null}
              <FaGithub
                onClick={() => window.open(link.github, "_blank")}
                className="cursor-pointer dark:text-white"
              />
            </div>
          </div>
          <p className="text-xs dark:text-gray-300 mb-2">{date}</p>
          <p className="mb-3 font-normal text-gray-700 dark:text-gray-400">
            {content}
          </p>
        </div>
        <div className="flex flex-wrap gap-1">
          {stack.map((techno, index) => (
            <p
              key={index}
              className="px-2 text-sm text-black bg-blue-100 dark:text-white dark:bg-blue-600 rounded-lg"
            >
              {techno}
            </p>
          ))}
        </div>
      </div>
    </div>
  );
}

export default ProjectCard;

// src/components/ProjectCard.vue
<script setup>
defineProps({
  project: {
    type: Object,
    required: true,
  },
});
</script>

<template>
  <article class="flex flex-col h-full bg-slate-800 rounded-2xl">
    <div
      class="h-72 rounded-t-2xl bg-cover bg-center"
      :style="{ backgroundImage: 'url(' + project.image + ')' }"
    ></div>
    <div
      class="bg-transparent p-4 rounded-b-2xl flex flex-col gap-5 justify-between flex-grow"
    >
      <div class="flex flex-col gap-3">
        <div class="flex justify-between items-center gap-3">
          <h3 class="text-2xl font-medium">{{ project.title }}</h3>
          <p class="text-xs md:text-sm text-right text-slate-500">
            {{ project.date }}
          </p>
        </div>
        <p class="font-light text-slate-300">{{ project.content }}</p>
      </div>
      <div class="flex flex-col gap-5">
        <div class="flex flex-wrap gap-x-2 gap-y-1">
          <span
            v-for="item in project.stack"
            :key="item"
            class="text-slate-300 border border-slate-700 rounded-full py-0.5 px-1.5 text-xs font-medium"
          >
            {{ item }}
          </span>
        </div>

        <div>
          <div>
            <a
              v-if="project.link.deployed"
              :href="project.link.deployed"
              target="_blank"
              class="text-sm font-semibold bg-gradient-to-r from-orange-400 to-pink-400 bg-clip-text text-transparent group hover:bg-gradient-to-r hover:from-pink-400 hover:to-orange-400 transition-colors duration-300"
            >
              View project
            </a>
            <span v-if="project.link.deployed && project.link.github"> | </span>
            <a
              v-if="project.link.github"
              :href="project.link.github"
              target="_blank"
              class="text-sm font-semibold bg-gradient-to-r from-orange-400 to-pink-400 bg-clip-text text-transparent group hover:bg-gradient-to-r hover:from-pink-400 hover:to-orange-400 transition-colors duration-300"
            >
              View GitHub repository
            </a>
          </div>
        </div>
      </div>
    </div>
  </article>
</template>
